### ISSUE TITLE
hpcnotebook setup raises TypeError

### ISSUE THREAD

**Issue by dirmeier** [rokroskar/sparkhpc#13]
Dear Rok,

setting up a `hpcnotebook` raises a `TypeError`. Am I missing something here or calling it incorrectly? Same thing happens on a cluster. I am using a python3 virtual environment.

```bash
/Users/simondi/anaconda3/envs/py35/bin/hpcnotebook setup
INFO:hpcnotebook:
            This script will create a Jupyter notebook profile for working remotely.
            When it is finished, you can find the configuration in /Users/simondi/.jupyter_notebook.
            First, please enter a *new* password for your Jupyter notebook:

Enter password:
Verify password:
INFO:hpcnotebook:Creating an SSL certificate to enable a secure connection; the certificate will be in your ~/.ssh directory
Traceback (most recent call last):
  File "/Users/simondi/anaconda3/envs/py35/bin/hpcnotebook", line 4, in <module>
    __import__('pkg_resources').run_script('sparkhpc==0.3.post2', 'hpcnotebook')
  File "/Users/simondi/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/Users/simondi/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/Users/simondi/anaconda3/envs/py35/lib/python3.5/site-packages/sparkhpc-0.3.post2-py3.5.egg/EGG-INFO/scripts/hpcnotebook", line 213, in <module>
  File "/Users/simondi/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simondi/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/simondi/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simondi/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simondi/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/simondi/anaconda3/envs/py35/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/simondi/anaconda3/envs/py35/lib/python3.5/site-packages/sparkhpc-0.3.post2-py3.5.egg/EGG-INFO/scripts/hpcnotebook", line 121, in setup
TypeError: a bytes-like object is required, not 'str'
```

Cheers,
Simon

**Comment by rokroskar** [comment]
thanks for pointing that out, I hadn't made sure that script was python 3 compatible. Can you try with 82c2b2e2b9e50c1dfbabf07a38cdfdb98de5858a?

**Comment by dirmeier** [comment]
Yes, its working! Thanks. I'll close this.
